import type { SimulationSettingsData } from "@epanet-js/ejsdb";

export const aSimulationSettings: SimulationSettingsData = {
  version: "v1",
  timing: {
    duration: 0,
    hydraulicTimestep: 3600,
    reportTimestep: 3600,
    patternTimestep: 3600,
  },
  globalDemandMultiplier: 1,
  demandModel: "DDA",
  minimumPressure: 0,
  requiredPressure: 0.1,
  pressureExponent: 0.5,
  emitterExponent: 0.5,
  backflowAllowed: true,
  qualitySimulationType: "none",
  qualityChemicalName: "Chemical",
  qualityMassUnit: "mg/L",
  qualityTraceNodeId: null,
  tolerance: 0.01,
  diffusivity: 1,
  reactionBulkOrder: 1,
  reactionWallOrder: 1,
  reactionTankOrder: 1,
  reactionGlobalBulk: 0,
  reactionGlobalWall: 0,
  reactionLimitingPotential: 0,
  reactionRoughnessCorrelation: 0,
  reportEnergy: false,
  energyGlobalEfficiency: 75,
  energyGlobalPrice: 0,
  energyGlobalPatternId: null,
  energyDemandCharge: 0,
  statusReport: "NO",
};
